[package]
name = "bbq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
atomic = "0.5.1"


[build-dependencies]
gpr = "0.1.2"
